name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: checkout
      uses: actions/checkout@v2

    - name: deps
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: build
      run: go build -race -v .../..
    
    - name: vet
      run: go vet -race -v .../..

    - name: test
      run: go test -race -v .../..
